"""add confidence and evidence to resume analysis

Revision ID: d745f53fb248
Revises: 7bceda78ae84
Create Date: 2026-08-08 10:28:54.673080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd745f53fb248'
down_revision: Union[str, Sequence[str], None] = '7bceda78ae84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume_analysis', sa.Column('confidence', sa.Float(), nullable=False))
    op.add_column('resume_analysis', sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume_analysis', 'evidence')
    op.drop_column('resume_analysis', 'confidence')
    # ### end Alembic commands ###
